server:
    port: 8080

spring:
    application:
        name: config-client
    profiles:
        active: dev
    cloud:
        config:
            uri: http://localhost:8888/

management:
    endpoints:
        web:
            exposure:
                include: '*'
    security:
        enabled: false